[package]
name = "clini"
version = "0.1.0"
authors = ["Dominic Green <dominicgreen1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
exitcode = "1.1.2"
rust-ini = "0.16"
